services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: leenkz
      POSTGRES_USER: leenkz
      POSTGRES_PASSWORD: leenkz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leenkz"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Leenkz API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://leenkz:leenkz@postgres/leenkz
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./leenkz:/app/leenkz
    command: ["uv", "run", "leenkz", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Nginx for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - api

volumes:
  postgres_data: 